### ISSUE TITLE
torchvision==0.10.0

### ISSUE THREAD

**Issue by bertoni9** [openpifpaf/openpifpaf#452]
Hi @svenkreiss,

When pip installing the latest version of openpifpaf, with torch==1.9.0 and torchvision==0.10.0, I encounter the error below during prediction. When using torchvision==0.9 and torch==1.8 everything works perfectly, so just to know whether you are having similar issues.

Thanks!
Lorenzo

```
python -m openpifpaf.predict --glob /Users/lorenzo/Desktop/test_image.jpeg -o /Users/lorenzo/Desktop/ --instance-threshold 0.1                     lorenzo-wayve
INFO:__main__:neural network device: cpu (CUDA available: False, count: 0)
INFO:openpifpaf.predictor:neural network device: cpu (CUDA available: False, count: 0)
Traceback (most recent call last):
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/openpifpaf/predict.py", line 133, in <module>
    main()
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/openpifpaf/predict.py", line 111, in main
    for pred, _, meta in predictor.images(
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/openpifpaf/predictor.py", line 129, in images
    yield from self.dataset(data, **kwargs)
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/openpifpaf/predictor.py", line 90, in dataset
    yield from self.dataloader(dataloader)
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/openpifpaf/predictor.py", line 93, in dataloader
    for batch_i, item in enumerate(dataloader):
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/openpifpaf/datasets/image_list.py", line 25, in __getitem__
    processed_image, anns, meta = self.preprocess(image, anns, meta)
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/openpifpaf/transforms/compose.py", line 15, in __call__
    args = p(*args)
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/openpifpaf/transforms/compose.py", line 15, in __call__
    args = p(*args)
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/openpifpaf/transforms/image.py", line 24, in __call__
    image = self.image_transform(image)
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 97, in __call__
    return F.to_tensor(pic)
  File "/Users/lorenzo/opt/miniconda3/envs/openpifpaf/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 129, in to_tensor
    np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
TypeError: __array__() takes 1 positional argument but 2 were given
```

**Comment by svenkreiss** [comment]
It's actually due to an upgrade in pillow. Try installing the previous pillow 8.2.0. The main branch requires that.

**Comment by bertoni9** [comment]
Ok thanks, it works!
PS: when running `pip install openpifpaf` at the moment is still installing Pillow=8.3 (with openpifpaf=0.12.11).

**Comment by svenkreiss** [comment]
Yes. I made a new release to pypi only now. It's still building the binaries.
