### ISSUE TITLE
Can't evaluate whole body keypoints

### ISSUE THREAD

**Issue by twmht** [openpifpaf/openpifpaf#457]
Hi,

I follow the tutorial

```bash
python3 -m openpifpaf.eval --dataset=wholebody --checkpoint=shufflenetv2k16-wholebody --force-complete-pose --seed-threshold=0.2 --loader-workers=16 --wholebody-val-annotations=<PathToTheOriginalCOCOWholeBodyAnnotations>/coco_wholebody_val_v1.0.json --wholebody-val-image-dir=<COCO_val_image_dir>
```

but got

```
Evaluate annotation type *keypoints_body*
Traceback (most recent call last):
    File "/home/acer/.pyenv/versions/3.7.1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
    File "/home/acer/.pyenv/versions/3.7.1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
    File "/home/shared/nfs/acer-share/openpifpaf/openpifpaf/eval.py", line 245, in <module>
    main()
    File "/home/shared/nfs/acer-share/openpifpaf/openpifpaf/eval.py", line 241, in main
    evaluate(args)
    File "/home/shared/nfs/acer-share/openpifpaf/openpifpaf/eval.py", line 184, in evaluate
    this_metric_stats  =  metric.stats()
    File "/home/shared/nfs/acer-share/openpifpaf/openpifpaf/plugins/wholebody/wholebody_metric.py", line 202, in stats
    'stats': self._stats().tolist(),
    File "/home/shared/nfs/acer-share/openpifpaf/openpifpaf/plugins/wholebody/wholebody_metric.py", line 103, in _stats
    eval_body.evaluate()
    File "/home/shared/nfs/acer-share/xtcocoapi/xtcocotools/cocoeval.py", line 257, in evaluate
    for imgId in p.imgIds
    File "/home/shared/nfs/acer-share/xtcocoapi/xtcocotools/cocoeval.py", line 258, in <dictcomp>
    for catId in catIds}
    File "/home/shared/nfs/acer-share/xtcocoapi/xtcocotools/cocoeval.py", line 368, in computeOks
    dx  =  xd - xg
    ValueError: operands could not be broadcast together with shapes (17,) (133,)
```

any idea?

**Comment by DuncanZauss** [comment]
Hi @twmht ,
Thanks for your interest in OpenPifPaf WholeBody!
I believe that you are using the wrong validation annotation file, i.e. the original MS COCO annotation file with only 17 keypoints per person. Could you please verify that the path after "--wholebody-val-annotations" points to [this file](https://drive.google.com/file/d/1N6VgwKnj8DeyGXCvp1eYgNbRmw6jdfrb/view)?

**Comment by twmht** [comment]
@DuncanZauss 

In face i used `person_keypoints_val2017_wholebody_pifpaf_style.json` from 

```
wget https://github.com/DuncanZauss/openpifpaf_assets/releases/download/v0.1.0/person_keypoints_val2017_wholebody_pifpaf_style.json -O /<PathToYourMSCOCO>/data-mscoco/annotations
```

So what is the usage of `person_keypoints_val2017_wholebody_pifpaf_style.json`?

**Comment by DuncanZauss** [comment]
I see!  At training time we compute the loss on the validation set with those annotations after every epoch. `person_keypoints_val2017_wholebody_pifpaf_style` contains basically the same information as `coco_wholebody_val_v1.0.json`, but is just in a different format, so that we can always use the same dataloader across different datasets that we use for OpenPifPaf. However, for evaluation we follow the [evaluation protocol from the authors of COCO WholeBody](https://github.com/jin-s13/COCO-WholeBody/tree/master/evaluation), and thus you need to provide the original evaluation file `coco_wholebody_val_v1.0.json` for evaluation.

In any case, thanks for pointing this out! I will try to make the tutorial clearer.

**Comment by twmht** [comment]
@DuncanZauss 

it helps.

thank you.
