### ISSUE TITLE
training with shufflenetv2k16: AttributeError: module 'signal' has no attribute 'SIGTERM'

### ISSUE THREAD

**Issue by SanjunLiu** [openpifpaf/openpifpaf#507]
INFO:openpifpaf.network.trainer:model written: outputs/shufflenetv2k16-211018-044842-cocokp-o10s.pkl.epoch000
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/dl/openpifpaf/openpifpaf/train.py", line 210, in <module>
    main()
  File "/workspace/dl/openpifpaf/openpifpaf/train.py", line 206, in main
    trainer.loop(train_loader, val_loader, start_epoch=start_epoch)
  File "/workspace/dl/openpifpaf/openpifpaf/network/trainer.py", line 158, in loop
    self.train(train_scenes, epoch)
  File "/workspace/dl/openpifpaf/openpifpaf/network/trainer.py", line 289, in train
    for batch_idx, (data, target, _) in enumerate(scenes):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 942, in __init__
    _utils.signal_handling._set_SIGCHLD_handler()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 57, in _set_SIGCHLD_handler
    previous_handler = signal.getsignal(signal.SIGCHLD)
AttributeError: module 'signal' has no attribute 'getsignal'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/util.py", line 330, in _exit_function
    p._popen.terminate()
  File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 62, in terminate
    self._send_signal(signal.SIGTERM)
AttributeError: module 'signal' has no attribute 'SIGTERM'

**Comment by senanursahin** [comment]
I'm getting the same error on Ubuntu 20.04 while trying to run _train_ command. I have the attribute when I open a python shell in my virtual env (python 3.9) and call the attribute in there, the screenshot is in below.
![Screenshot from 2022-05-02 22-19-35](https://user-images.githubusercontent.com/48882047/166311338-c5f39b8b-bd44-4310-90e7-b1a8b50a3a40.png)

In this blog (https://bugs.python.org/issue28946) it's said the reason is having a file named as signal.py in the project, but I wonder how your automated deployments/tests are ok but I'm having the issue. 

Looking forward to your response, thanks in advance.
