### ISSUE TITLE
Import error.

### ISSUE THREAD

**Issue by bhargav-sudo** [openpifpaf/openpifpaf#513]
Hi, I want try this project in my local machine.
but it says error like this when i run a sample.

used command : python -m openpifpaf.predict --help

Error output : 

File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/openpifpaf/openpifpaf/__init__.py", line 11, in <module>
    cpp_extension.register_ops()
  File "/openpifpaf/openpifpaf/cpp_extension.py", line 25, in register_ops
    raise ImportError
ImportError

Is there any chance to clear this error.

Thanks.

**Comment by svenkreiss** [comment]
You need to install openpifpaf in order for the C++ extension to get compiled. Either `pip3 install openpifpaf` or if you have a local copy `pip3 install -e .`.

**Comment by bhargav-sudo** [comment]
Thanks for the update.

does this works on videos..?

**Comment by svenkreiss** [comment]
Sure. Try the `.video` instead of `.predict`. Some sparse documentation is here: https://openpifpaf.github.io/cli_help.html#video

**Comment by bhargav-sudo** [comment]
Hi It throws a new error like this.
**Command used** : python3 -m openpifpaf.predict docs/coco/000000081988.jpg --image-output

**Error**  : 
INFO:__main__:neural network device: cuda (CUDA available: True, count: 1)
Downloading: "http://github.com/openpifpaf/torchhub/releases/download/v0.13/shufflenetv2k16-210820-232500-cocokp-slurm726069-edge513-o10s-7189450a.pkl" to /.cache/torch/hub/checkpoints/shufflenetv2k16-210820-232500-cocokp-slurm726069-edge513-o10s-7189450a.pkl
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1442, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)


Thanks

**Comment by svenkreiss** [comment]
This one has nothing to do with OpenPifPaf. Something about how your Python does web requests is funny. 

If you cannot fix that on your system, try downloading this checkpoint with a normal browser and then use the `--checkpoint` command line argument to use that checkpoint.

**Comment by bhargav-sudo** [comment]
Hi when I worked on videos.
It shows error. 
Command : python3 -m openpifpaf.video --source /Downloads/input.mp4 --checkpoint /Downloads/shufflenetv2k16-210820-232500-cocokp-slurm726069-edge513-o10s-7189450a.pkl --video-output  --json-output

INFO:openpifpaf.decoder.cifcaf:annotations 1: [13]
INFO:openpifpaf.predictor:batch 0: no-file-name
INFO:__main__:frame 1, loop time = 1302ms (pre = 56.1ms, post = 29.1ms), FPS = 0.8
INFO:openpifpaf.decoder.cifcaf:annotations 1: [13]
INFO:openpifpaf.predictor:batch 1: no-file-name
INFO:__main__:frame 2, loop time = 1082ms (pre = 55.7ms, post = 130.3ms), FPS = 0.9
WARNING:matplotlib.animation:MovieWriter stderr:
[h264_v4l2m2m @ 0x563afd770f80] Could not find a valid device
[h264_v4l2m2m @ 0x563afd770f80] can't configure encoder
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height


Does we need to set video parameters by ourselfes.
Thanks.

**Comment by svenkreiss** [comment]
No. Something seems up with the video codecs on your system. The ffmpeg backend does not find a h264 codec?
Can you run `ffmpeg -codecs`? Do you see an h264 encoder?

**Comment by bhargav-sudo** [comment]
Yes, I can see.
![Screenshot from 2021-11-22 15-43-04](https://user-images.githubusercontent.com/57169077/142843244-7856c1d6-e0aa-427b-ad36-768aa98a6fcd.png)

**Comment by svenkreiss** [comment]
I don't know what is wrong. Can you try to run something like the lines below? They are pure matplotlib to test to write a video output:

```
import matplotlib.animation
import matplotlib.pyplot as plt
writer = matplotlib.animation.writers['ffmpeg'](fps=10.0)
fig, ax = plt.subplots(1, 1)
writer.setup(fig, 'test_animation_output.mp4')
writer.grab_frame()
writer.finish()
```

Do any of these lines lead to an output like you had before like `Could not find a valid device`?

**Comment by bhargav-sudo** [comment]
Hi,
I installed ffmpeg version which supports h264code.
it works.

When I run that command again it says that my checkpoint was not found. But it is downloaded.

**Error :** 
Exception: Checkpoint "/Downloads/shufflenetv2k16-210820-232500-cocokp-slurm726069-edge513-o10s-7189450a.pkl" not found. Pre-trained checkpoints: ['shufflenetv2k30-animalpose', 'shufflenetv2k16-apollo-24', 'shufflenetv2k16-apollo-66', 'shufflenetv2k30-apollo-66', 'mobilenetv2', 'mobilenetv3small', 'mobilenetv3large', 'resnet50', 'shufflenetv2k16', 'shufflenetv2k16-withdense', 'shufflenetv2k30', 'swin_s', 'swin_b', 'swin_t_input_upsample', 'mobilenetv3small-cocodet', 'resnet18-cocodet', 'resnet50-crowdpose', 'shufflenetv2k16-nuscenes', 'tshufflenetv2k16', 'tshufflenetv2k30', 'shufflenetv2k16-wholebody', 'shufflenetv2k30-wholebody']

Thanks.

**Comment by svenkreiss** [comment]
Video reading is handled by opencv. Can you test whether that is working in Python with `import cv2` and so on?

**Comment by svenkreiss** [comment]
Any success?

**Comment by wolfworld6** [comment]
> stalled ffmpeg version which supports h264code.

hello，have you solved it？
