### ISSUE TITLE
pip install openpifpaf==0.13.1 failed

### ISSUE THREAD

**Issue by shang0085** [openpifpaf/openpifpaf#531]
I am on windows10, Python 3.9.7, torch '1.10.1+cu102'

Error shown:

  ERROR: Command errored out with exit status 1:
   command: 'E:\Anaconda3\envs\torch\python.exe' 'E:\Anaconda3\envs\torch\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\user\AppData\Local\Temp\tmpg9_ss3ny'
       cwd: C:\Users\user\AppData\Local\Temp\pip-install-aeb9lodd\openpifpaf_86c2d74c9b0f476dba8ddf25357cc01a
  Complete output (44 lines):
  C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\torch\package\_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: 
No module named 'numpy' (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:67.)
    _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
  No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2'
  running egg_info
  Traceback (most recent call last):
    File "E:\Anaconda3\envs\torch\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "E:\Anaconda3\envs\torch\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "E:\Anaconda3\envs\torch\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel  
      return self._get_build_requires(
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 61, in <module>
      setuptools.setup(
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 299, in run
      self.find_sources()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 306, in find_sources
      mm.run()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 541, in run
      self.add_defaults()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 585, in add_defaults
      self.read_manifest()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\command\sdist.py", line 195, in read_manifest
      self.filelist.append(line)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 483, in append
      path = convert_path(item)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-7v7_bokn\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 180, in convert_path
      raise ValueError("path '%s' cannot be absolute" % pathname)
  ValueError: path '/home/runner/work/openpifpaf/openpifpaf/src/openpifpaf/csrc/src/caf_scored.cpp' cannot be absolute
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/79/32/a9c53bb32c96b0ee7b38657b4723153f507dc19fdf94168054da6682d5fd/openpifpaf-0.13.1.tar.gz#sha256=a34ad24b6844c91d44c1b3ac632f35eebf4d3b605bc24ca5dda0ee8d26c7c0e9 (from https://pypi.org/simple/openpifpaf/) (requires-python:>=3.6). Command errored out with exit status 1: 
'E:\Anaconda3\envs\torch\python.exe' 'E:\Anaconda3\envs\torch\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\user\AppData\Local\Temp\tmpg9_ss3ny' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement openpifpaf==0.13.1 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.11.6, 0.11.7, 0.11.8, 0.11.9, 0.12a1, 0.12a3, 0.12a4, 0.12a6, 0.12b1, 0.12b2, 0.12b4, 0.12, 0.12.1, 0.12.2, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.10, 0.12.11, 0.12.12, 0.12.13, 0.12.14, 0.13.0, 0.13.1)
ERROR: No matching distribution found for openpifpaf==0.13.1

Anyone facing this problem?

**Comment by jdonley** [comment]
I am also getting the same error on Windows.

**Comment by svenkreiss** [comment]
Thanks for reporting this problem with the full error message. That helps a lot.

Ignore the "add zip format to sdist" above. That is not the issue.

I am putting in a change that might help here: https://github.com/openpifpaf/openpifpaf/pull/545
However, I don't know why this happens. We have tests on Windows that run on every release and it didn't show this problem. It could be an older version of setuptools. Can you try upgrading setuptools with something like `pip3 install --upgrade setuptools`? Similarly, keeping on the latest version of `pip` is also a good idea. Otherwise, I think you'd need to wait until 0.13.3 with the above fix and try again then.

**Comment by svenkreiss** [comment]
0.13.3 is out now. Please re-open this issue if the problem persists.

Btw, the successful test log on Windows of the release 0.13.3 is here: https://github.com/openpifpaf/openpifpaf/runs/5650316778?check_suite_focus=true
Maybe that also helps to identify the problem.
