### ISSUE TITLE
undefined symbol (again)

### ISSUE THREAD

**Issue by bach05** [openpifpaf/openpifpaf#532]
Hi, 
I am facing the same problem of #510. I tried: 
```
pip3 install matplotlib openpifpaf
[...]
Successfully installed boto-2.49.0 certifi-2021.10.8 charset-normalizer-2.0.10 cycler-0.11.0 dataclasses-0.8 future-0.18.2 idna-3.3 importlib-metadata-4.8.3 kiwisolver-1.3.1 matplotlib-3.3.4 numpy-1.19.5 openpifpaf-0.13.1 pillow-8.4.0 pyparsing-3.0.6 pysparkling-0.6.1 python-dateutil-2.8.2 python-json-logger-2.0.2 pytz-2021.3 requests-2.27.1 six-1.16.0 torch-1.9.0+rocm4.2 torchvision-0.11.2 typing-extensions-4.0.1 urllib3-1.26.8 zipp-3.6.0

python3 -m openpifpaf.predict docs/coco/000000081988.jpg --image-output

```
But I got the error: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/tiago/.local/lib/python3.6/site-packages/openpifpaf/__init__.py", line 10, in <module>
    cpp_extension.register_ops()
  File "/home/tiago/.local/lib/python3.6/site-packages/openpifpaf/cpp_extension.py", line 26, in register_ops
    torch.ops.load_library(ext_specs.origin)
  File "/home/tiago/.local/lib/python3.6/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/tiago/.local/lib/python3.6/site-packages/openpifpaf/_cpp.so: undefined symbol: _ZN5torch6detail10class_baseC2ERKSsS3_SsRKSt9type_infoS6_
```
The proposed solution does not work properly, since `pip install --no-build-isolation openpifpaf`, returns: 
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting openpifpaf
  Using cached openpifpaf-0.11.0.tar.gz (201 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lGYDJX/openpifpaf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lGYDJX/openpifpaf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4ZyO71
         cwd: /tmp/pip-install-lGYDJX/openpifpaf/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lGYDJX/openpifpaf/setup.py", line 57, in <module>
        long_description=open('README.md', encoding='utf-8').read(),
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
While `pip3 install --no-build-isolation openpifpaf`:
```
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --no-build-isolation
```

What 's wrong? Thank you for your help!

**Comment by svenkreiss** [comment]
The last code block indicates your pip3 is too old. Maybe try `pip3 install --upgrade pip`?
The second to last code block shows indicates that your pip is connected to Python 2. That is not supported. You always need to use pip3.

The install and test logs for Linux Python 3.6 are at https://github.com/openpifpaf/openpifpaf/runs/4622465587?check_suite_focus=true Does anything stick out how that is different to your system?
Please note that Python 3.6 is now past the official Python end-of-life date and not supported anymore.
