### ISSUE TITLE
torchscript and onnx exportation problems

### ISSUE THREAD

**Issue by derbysolto** [openpifpaf/openpifpaf#533]
Hey guys, great work.

I wanted to test OpenPifPaf Car Keypoint model on Android. So I started converting the model to torchscript using the export_torchscript.py file provided by version 0.13.0. Once I convert the model to torchscript, I optimize it to mobile and convert it to .ptl format. According to this: https://pytorch.org/mobile/android/ . Once I finish the conversion to .ptl format, I should be able to run the OpenPifPaf on an Android mobile device.

However, during the exportation to torchscript, when I loaded the file in a different script using the following

```
import torch

model = torch.jit.load("./shufflenetv2k16-apollo-24.torchscript.pt")
```

without the OpenPifPaf module imported, it throw me the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/derby/anaconda3/envs/vps/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: 
Unknown type name '__torch__.torch.classes.openpifpaf_decoder.CifCaf':
Serialized   File "code/__torch__.py", line 26
  training : bool
  _is_full_backward_hook : Optional[bool]
  cpp_decoder : __torch__.torch.classes.openpifpaf_decoder.CifCaf
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  cif_stride : int
  caf_stride : int
```

However, when I import the OpenPifPaf module, I'm able to run the inference in an image.

The other option that I have to run the OpenPifPaf model on Android is by using ONNX. I converted the model by using the provided script export_onnx.py. However, when I loaded the ONNX model and apply it to an image (inference), it gave me the following tensor format:
`
(Pdb) pred_onnx[1].shape
(1, 19, 8, 13, 17)
(Pdb) pred_onnx[0].shape
(1, 17, 5, 13, 17)
`
It seems that the decoder head is lacking in the model exportation. But, I do not need to import OpenPifPaf to run ONNX exported model. However, I have to figure out how to decode both heads.

So I would like to ask the following:
1. Is the export_torchscript.py broken or am I missing something?
2. How could I decode the output tensor, as reported above, to have only the (x, y, confidence, scale) for each keypoint.

Thanks in advance!

**Comment by svenkreiss** [comment]
Thanks for spending this time to write the careful issue. Sounds like things work as expected. The decoder is based on a pytorch plugin in C++ and must be imported available in some form and the import that you have in the first part does that.

For ONNX, I don't know of a quick way to make the decoder available. You might have to do that yourself. We do have the cpp directory that contains a cmake file which you can use to make an openpifpaf library that contains the decoder. That path is very experimental.
