### ISSUE TITLE
Apollo 3D dataloader

### ISSUE THREAD

**Issue by srikanthmalla** [openpifpaf/openpifpaf#550]
Hi,
Thank you for open sourcing such an amazing code. I want to use apollocar3d dataloader for keypoint detection. But the current dataloader for apollo3d [https://github.com/openpifpaf/openpifpaf/blob/main/src/openpifpaf/plugins/apollocar3d/apollo_kp.py](https://github.com/openpifpaf/openpifpaf/blob/main/src/openpifpaf/plugins/apollocar3d/apollo_kp.py) has manually fixed args and openpifpaf encoders. To use apollocar3d dataloader for any baseline I created the following script using your dataloader, but it gives error pasted below. The error is from the transforms in openpifpaf, I verified that the CocoDataset is reading data and annotations. I remove preprocessing step I get the error saying `each element in list of batch should be of equal size`. Could you please help me fix this.

Thank you!

I Installed openpifpaf library using `pip install openpifpaf`

-  **CODE**

```
import torch
import numpy as np
from pycocotools.coco import COCO
from torch.utils.data import DataLoader, Dataset

from openpifpaf import encoder, headmeta, metric, transforms
from openpifpaf.datasets import collate_images_anns_meta, collate_images_targets_meta
from openpifpaf.plugins.coco import CocoDataset as CocoLoader

from .constants import get_constants, training_weights_local_centrality
from .metrics import MeanPixelError

class ApolloKp():
		"""
		DataLoader for the Apollocar3d Dataset.
		"""
		def __init__(self, args):
				self.args = args
				self.train_annotations = args.data_dir+"annotations/apollo_keypoints_24_train.json"
				self.val_annotations = args.data_dir+"annotations/apollo_keypoints_24_val.json"
				self.eval_annotations = self.val_annotations
				self.train_image_dir = args.data_dir+"images/train/"
				self.val_image_dir =  args.data_dir+"images/val/"
				# print(self.train_image_dir)
				self.eval_image_dir = self.val_image_dir
				self.debug = False
				self.pin_memory = False

				if self.args.apollo_use_24_kps:
						(self.CAR_KEYPOINTS, self.CAR_SKELETON, self.HFLIP, self.CAR_SIGMAS, self.CAR_POSE,
						 self.CAR_CATEGORIES, self.CAR_SCORE_WEIGHTS) = get_constants(24)
				else:
						(self.CAR_KEYPOINTS, self.CAR_SKELETON, self.HFLIP, self.CAR_SIGMAS, self.CAR_POSE,
						 self.CAR_CATEGORIES, self.CAR_SCORE_WEIGHTS) = get_constants(66)

		def _preprocess(self, augmentation=False):
				# encoders = (encoder.Cif(self.head_metas[0], bmin=self.b_min),
										# encoder.Caf(self.head_metas[1], bmin=self.b_min))

				if not augmentation:
						return transforms.Compose([
								transforms.NormalizeAnnotations(),
								transforms.RescaleAbsolute(self.args.square_edge),
								transforms.CenterPad(self.args.square_edge),
								transforms.EVAL_TRANSFORM,
								# transforms.Encoders(encoders),
						])

				if self.args.extended_scale:
						rescale_t = transforms.RescaleRelative(
								scale_range=(0.2 * self.args.rescale_images,
														 2.0 * self.args.rescale_images),
								power_law=True, stretch_range=(0.75, 1.33))
				else:
						rescale_t = transforms.RescaleRelative(
								scale_range=(0.33 * self.args.rescale_images,
														 1.33 * self.args.rescale_images),
								power_law=True, stretch_range=(0.75, 1.33))

				return transforms.Compose([
						transforms.NormalizeAnnotations(),
						# transforms.AnnotationJitter(),
						transforms.RandomApply(transforms.HFlip(self.CAR_KEYPOINTS, self.HFLIP), 0.5),
						rescale_t,
						transforms.RandomApply(transforms.Blur(), self.args.blur),
						transforms.RandomChoice(
								[transforms.RotateBy90(),
								 transforms.RotateUniform(30.0)],
								[self.args.orientation_invariant, 0.2],
						),
						transforms.Crop(self.args.square_edge, use_area_of_interest=True),
						transforms.CenterPad(self.args.square_edge),
						transforms.MinSize(min_side=32.0),
						transforms.TRAIN_TRANSFORM,
						# transforms.Encoders(encoders),
				])

		def train_loader(self):
				train_data = CocoLoader(
						image_dir=self.train_image_dir,
						ann_file=self.train_annotations,
						preprocess=self._preprocess(augmentation=True),
						annotation_filter=True,
						min_kp_anns=self.args.min_kp_anns,
						category_ids=[1],
				)
				return torch.utils.data.DataLoader(
						train_data, batch_size=self.args.batch_size, shuffle=not self.debug,
						pin_memory=self.pin_memory, num_workers=self.args.loader_workers, drop_last=True,
						collate_fn=collate_images_targets_meta)

		def val_loader(self):
				val_data = CocoLoader(
						image_dir=self.val_image_dir,
						ann_file=self.val_annotations,
						preprocess=self._preprocess(),
						annotation_filter=True,
						min_kp_anns=self.args.min_kp_anns,
						category_ids=[1],
				)
				return torch.utils.data.DataLoader(
						val_data, batch_size=self.args.batch_size, shuffle=False,
						pin_memory=self.pin_memory, num_workers=self.args.loader_workers, drop_last=True,
						collate_fn=collate_images_targets_meta)

		# TODO: make sure that 24kp flag is activated when evaluating a 24kp model
		def metrics(self):
				return [metric.Coco(
						COCO(self.eval_annotations),
						max_per_image=24,
						category_ids=[1],
						iou_type='keypoints',
						keypoint_oks_sigmas=self.CAR_SIGMAS
				), MeanPixelError()]

```

-  **ERROR**
```
    data = self._next_data()
  File "/home/user/anaconda3/envs/pose2d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/user/anaconda3/envs/pose2d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/user/anaconda3/envs/pose2d/lib/python3.6/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pose2d/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/anaconda3/envs/pose2d/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/anaconda3/envs/pose2d/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/anaconda3/envs/pose2d/lib/python3.6/site-packages/openpifpaf/plugins/coco/dataset.py", line 128, in __getitem__
    image, anns, meta = self.preprocess(image, anns, meta)
  File "/home/user/anaconda3/envs/pose2d/lib/python3.6/site-packages/openpifpaf/transforms/compose.py", line 15, in __call__
    args = p(*args)
  File "/home/user/anaconda3/envs/pose2d/lib/python3.6/site-packages/openpifpaf/transforms/scale.py", line 143, in __call__
    return _scale(image, anns, meta, target_w, target_h, self.resample, fast=self.fast)
  File "/home/user/anaconda3/envs/pose2d/lib/python3.6/site-packages/openpifpaf/transforms/scale.py", line 63, in _scale
    im_np = scipy.ndimage.zoom(im_np, (target_h / h, target_w / w, 1), order=order)
AttributeError: 'NoneType' object has no attribute 'ndimage'
```

**Comment by svenkreiss** [comment]
That transform requires scipy, `pip3 install scipy` should do the trick. 

It comes with the `train` dependencies of openpifpaf. So `pip3 install "openpifpaf[train]"` should have pulled in scipy.
