### ISSUE TITLE
fine-tuning pretrained shufflenetv2k16-wholebody error - CAF size missmatch in Composite Loss 

### ISSUE THREAD

**Issue by tijanavukovic1** [openpifpaf/openpifpaf#556]
Hello,

I am using openpifpaf 0.13.3 repository with [this commit](https://github.com/openpifpaf/openpifpaf/tree/2d82d08522a316c80c9abce438f2fb7a547dc26f).

I want to fine-tune shufflenetv2k16-wholebody with pretrained model from your repository. When I set CLI argument `--checkpoint shufflenetv2k16-wholebody` while calling training, it downloads pretrained model from  [this link](http://github.com/DuncanZauss/openpifpaf_assets/releases/download/v0.1.0/sk16_wholebody.pkl), runs training process, but error in Composite Loss class occurred. The error is about that the third dimension of CAF output (which is 9) missmatches expected (which is 8) in Composite Loss class.

The comand with which I am running fine-tuning is:

` python3 -m openpifpaf.train --checkpoint shufflenetv2k16-wholebody --lr=0.0001 --momentum=0.95 --b-scale=3.0 --epochs=601 --lr-decay 130 140 --lr-decay-epochs=10 --batch-size=1 --weight-decay=1e-5 --dataset=wholebody --wholebody-upsample=2 --loader-workers=16 --wholebody-train-annotations=/app/source/data-mscoco/annotations/person_keypoints_train2017_wholebody_pifpaf_style.json --wholebody-val-annotations=/app/source/data-mscoco/annotations/person_keypoints_val2017_wholebody_pifpaf_style.json --wholebody-train-image-dir=/app/source/data-mscoco/images/train2017/ --wholebody-val-image-dir=/app/source/data-mscoco/images/val2017/ `

Here is the assertion error which occured during running:

```
INFO:openpifpaf.network.trainer:{'type': 'config', 'field_names': ['wholebody.cif.c', 'wholebody.cif.vec', 'wholebody.cif.scales', 'wholebody.caf.c', 'wholebody.caf.vec', 'wholebody.caf.scales']}
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/source/openpifpaf_wholebody/src/openpifpaf/train.py", line 238, in <module>
    main()
  File "/app/source/openpifpaf_wholebody/src/openpifpaf/train.py", line 234, in main
    trainer.loop(train_loader, val_loader, start_epoch=start_epoch)
  File "/app/source/openpifpaf_wholebody/src/openpifpaf/network/trainer.py", line 158, in loop
    self.train(train_scenes, epoch)
  File "/app/source/openpifpaf_wholebody/src/openpifpaf/network/trainer.py", line 294, in train
    loss, head_losses = self.train_batch(data, target, apply_gradients)
  File "/app/source/openpifpaf_wholebody/src/openpifpaf/network/trainer.py", line 183, in train_batch
    loss, head_losses = self.loss(outputs, targets)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/source/openpifpaf_wholebody/src/openpifpaf/network/losses/multi_head.py", line 29, in forward
    flat_head_losses = [ll
  File "/app/source/openpifpaf_wholebody/src/openpifpaf/network/losses/multi_head.py", line 31, in <listcomp>
    for ll in l(f, t)]
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/source/openpifpaf_wholebody/src/openpifpaf/network/losses/composite.py", line 250, in forward
    assert x.shape[2] == 1 + self.n_confidences + self.n_vectors * 2 + self.n_scales
AssertionError
Exiting

```

When I train shufflenetv2k16 backbone with wholebody keypoints from scratch and set path to that model as checkpoint, training process passes. I suppose that there is an issue with pretrained model which is downloaded from link and code from v0.13.3 version.

Thank you in advance!

**Comment by lozhn** [comment]
same issue on apollo with a custom dataset

**Comment by marco-lee25** [comment]
> 

I had the same issue too, but it seem that the head network (Composite Loss 3 to Composite Loss 4) had changed in 0.13 version, while the pre-trained model is in 0.12 version and lead to such error.
