### ISSUE TITLE
Compute_training_weights.py error

### ISSUE THREAD

**Issue by ZeynepRuveyda** [openpifpaf/openpifpaf#566]
Hello,
Do you have any idea why I get this error?

(env) (base) zeynep_automi_ai@anomalib:~/zeynep_anomalib/openpifpaf/Keypoint_Communities/src$ python Compute_training_weights.py
Traceback (most recent call last):
  File "/home/zeynep_automi_ai/zeynep_anomalib/openpifpaf/Keypoint_Communities/src/Compute_training_weights.py", line 314, in <module>
    create_weights_wholebody()
  File "/home/zeynep_automi_ai/zeynep_anomalib/openpifpaf/Keypoint_Communities/src/Compute_training_weights.py", line 192, in create_weights_wholebody
    draw_skeletons_wb(WHOLEBODY_STANDING_POSE, inverse_normalize(w_harm_cl_euclid, kps=kps),
  File "/home/zeynep_automi_ai/zeynep_anomalib/openpifpaf/Keypoint_Communities/src/Compute_training_weights.py", line 60, in draw_skeletons_wb
    from openpifpaf.annotation import Annotation  # pylint: disable=import-outside-toplevel
  File "/home/zeynep_automi_ai/zeynep_anomalib/openpifpaf/env/lib/python3.9/site-packages/openpifpaf/__init__.py", line 11, in <module>
    cpp_extension.register_ops()
  File "/home/zeynep_automi_ai/zeynep_anomalib/openpifpaf/env/lib/python3.9/site-packages/openpifpaf/cpp_extension.py", line 26, in register_ops
    torch.ops.load_library(ext_specs.origin)
  File "/home/zeynep_automi_ai/zeynep_anomalib/openpifpaf/env/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/zeynep_automi_ai/miniconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/zeynep_automi_ai/zeynep_anomalib/openpifpaf/env/lib/python3.9/site-packages/openpifpaf/_cpp.so: undefined symbol: _ZN5torch6detail10class_baseC2ERKSsS3_SsRKSt9type_infoS6_

**Comment by ZeynepRuveyda** [comment]
Do you have any idea on this error?

Thanks,
