### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available

### ISSUE THREAD

**Issue by beratersari** [openpifpaf/openpifpaf#580]
RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be openpifpaf

Hey, how can I solve this error? I tried to change Cuda version but other versions are not compatible with openpifpaf

**Comment by lozhn** [comment]
I have the same issue. I disabled cuda and found the next problem 
```python
Traceback (most recent call last):
  File "/home/farm/.conda/envs/pif/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/farm/.conda/envs/pif/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/farm/.conda/envs/pif/lib/python3.8/site-packages/openpifpaf/train.py", line 205, in <module>
    main()
  File "/home/farm/.conda/envs/pif/lib/python3.8/site-packages/openpifpaf/train.py", line 201, in main
    trainer.loop(train_loader, val_loader, start_epoch=start_epoch)
  File "/home/farm/.conda/envs/pif/lib/python3.8/site-packages/openpifpaf/network/trainer.py", line 158, in loop
    self.train(train_scenes, epoch)
  File "/home/farm/.conda/envs/pif/lib/python3.8/site-packages/openpifpaf/network/trainer.py", line 294, in train
    loss, head_losses = self.train_batch(data, target, apply_gradients)
  File "/home/farm/.conda/envs/pif/lib/python3.8/site-packages/openpifpaf/network/trainer.py", line 183, in train_batch
    loss, head_losses = self.loss(outputs, targets)
  File "/home/farm/.conda/envs/pif/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/farm/.conda/envs/pif/lib/python3.8/site-packages/openpifpaf/network/losses/multi_head.py", line 29, in forward
    flat_head_losses = [ll
  File "/home/farm/.conda/envs/pif/lib/python3.8/site-packages/openpifpaf/network/losses/multi_head.py", line 31, in <listcomp>
    for ll in l(f, t)]
  File "/home/farm/.conda/envs/pif/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/farm/.conda/envs/pif/lib/python3.8/site-packages/openpifpaf/network/losses/composite.py", line 250, in forward
    assert x.shape[2] == 1 + self.n_confidences + self.n_vectors * 2 + self.n_scales
AssertionError
```

Like [this](https://github.com/openpifpaf/openpifpaf/issues/556)
